# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tunnelconfig.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TunnelConfig(object):
    def setupUi(self, TunnelConfig):
        TunnelConfig.setObjectName("TunnelConfig")
        TunnelConfig.resize(508, 238)
        self.gridLayout = QtWidgets.QGridLayout(TunnelConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.label_remote_address = QtWidgets.QLabel(TunnelConfig)
        self.label_remote_address.setObjectName("label_remote_address")
        self.gridLayout.addWidget(self.label_remote_address, 1, 0, 1, 1)
        self.label_browser_open = QtWidgets.QLabel(TunnelConfig)
        self.label_browser_open.setObjectName("label_browser_open")
        self.gridLayout.addWidget(self.label_browser_open, 3, 0, 1, 1)
        self.label_local_port = QtWidgets.QLabel(TunnelConfig)
        self.label_local_port.setObjectName("label_local_port")
        self.gridLayout.addWidget(self.label_local_port, 0, 0, 1, 1)
        self.ssh_command = QtWidgets.QLineEdit(TunnelConfig)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.ssh_command.setFont(font)
        self.ssh_command.setReadOnly(True)
        self.ssh_command.setObjectName("ssh_command")
        self.gridLayout.addWidget(self.ssh_command, 4, 1, 1, 1)
        self.label_ssh_command = QtWidgets.QLabel(TunnelConfig)
        self.label_ssh_command.setObjectName("label_ssh_command")
        self.gridLayout.addWidget(self.label_ssh_command, 4, 0, 1, 1)
        self.label_proxy_host = QtWidgets.QLabel(TunnelConfig)
        self.label_proxy_host.setObjectName("label_proxy_host")
        self.gridLayout.addWidget(self.label_proxy_host, 2, 0, 1, 1)
        self.copy = QtWidgets.QPushButton(TunnelConfig)
        self.copy.setObjectName("copy")
        self.gridLayout.addWidget(self.copy, 4, 2, 1, 1)
        self.browser_open = QtWidgets.QLineEdit(TunnelConfig)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.browser_open.setFont(font)
        self.browser_open.setObjectName("browser_open")
        self.gridLayout.addWidget(self.browser_open, 3, 1, 1, 2)
        self.proxy_host = QtWidgets.QLineEdit(TunnelConfig)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.proxy_host.setFont(font)
        self.proxy_host.setObjectName("proxy_host")
        self.gridLayout.addWidget(self.proxy_host, 2, 1, 1, 2)
        self.remote_address = QtWidgets.QLineEdit(TunnelConfig)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.remote_address.setFont(font)
        self.remote_address.setStyleSheet("")
        self.remote_address.setObjectName("remote_address")
        self.gridLayout.addWidget(self.remote_address, 1, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(TunnelConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.local_port = QtWidgets.QSpinBox(TunnelConfig)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.local_port.setFont(font)
        self.local_port.setMaximum(65365)
        self.local_port.setSingleStep(1000)
        self.local_port.setProperty("value", 8443)
        self.local_port.setObjectName("local_port")
        self.horizontalLayout_2.addWidget(self.local_port)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 2)

        self.retranslateUi(TunnelConfig)
        self.buttonBox.accepted.connect(TunnelConfig.accept)
        self.buttonBox.rejected.connect(TunnelConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(TunnelConfig)
        TunnelConfig.setTabOrder(self.local_port, self.remote_address)
        TunnelConfig.setTabOrder(self.remote_address, self.proxy_host)
        TunnelConfig.setTabOrder(self.proxy_host, self.browser_open)
        TunnelConfig.setTabOrder(self.browser_open, self.ssh_command)
        TunnelConfig.setTabOrder(self.ssh_command, self.copy)

    def retranslateUi(self, TunnelConfig):
        _translate = QtCore.QCoreApplication.translate
        TunnelConfig.setWindowTitle(_translate("TunnelConfig", "Dialog"))
        self.label_remote_address.setText(_translate("TunnelConfig", "Remote Address"))
        self.label_browser_open.setText(_translate("TunnelConfig", "Address to Open"))
        self.label_local_port.setText(_translate("TunnelConfig", "Local Port"))
        self.label_ssh_command.setText(_translate("TunnelConfig", "SSH Command"))
        self.label_proxy_host.setText(_translate("TunnelConfig", "Proxy Host"))
        self.copy.setText(_translate("TunnelConfig", "Copy"))
        self.browser_open.setPlaceholderText(_translate("TunnelConfig", "https://127.0.0.1:8443"))
        self.proxy_host.setPlaceholderText(_translate("TunnelConfig", "proxy-host"))
        self.remote_address.setPlaceholderText(_translate("TunnelConfig", "10.10.10.10:443"))
